name: json_model
description: Gernerate model class from Json file.
version: 0.0.1
author: wendux <824783146@qq.com>
homepage: https://github.com/flutterchina/json_model

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  path: ^1.6.2
dev_dependencies:
  test: ^1.5.1
